2020-12-27 17:22:36,283 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 17:22:39,046 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 17:23:20,264 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 17:27:06,707 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 17:27:09,049 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 17:27:22,566 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 17:27:31,073 interview.admin 38 INFO     yoyo1_hr exported 2 candidate records
2020-12-27 17:28:48,082 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 17:28:50,469 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 17:29:26,964 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 17:40:27,660 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 17:52:47,921 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 17:53:21,075 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 17:53:23,275 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 17:53:26,729 django.request 224 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 1689, in changelist_view
    if not self.has_view_or_change_permission(request):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 533, in has_view_or_change_permission
    return self.has_view_permission(request, obj) or self.has_change_permission(request, obj)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 528, in has_view_permission
    request.user.has_perm('%s.%s' % (opts.app_label, codename_view)) or
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\models.py", line 294, in has_perm
    return _user_has_perm(self, perm, obj)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\models.py", line 200, in _user_has_perm
    for backend in auth.get_backends():
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\__init__.py", line 37, in get_backends
    return _get_backends(return_tuples=False)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\__init__.py", line 26, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\__init__.py", line 20, in load_backend
    return import_string(path)()
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_python3_ldap'
2020-12-27 17:53:55,404 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 17:53:58,979 django.request 224 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 1689, in changelist_view
    if not self.has_view_or_change_permission(request):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 533, in has_view_or_change_permission
    return self.has_view_permission(request, obj) or self.has_change_permission(request, obj)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 528, in has_view_permission
    request.user.has_perm('%s.%s' % (opts.app_label, codename_view)) or
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\models.py", line 294, in has_perm
    return _user_has_perm(self, perm, obj)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\models.py", line 200, in _user_has_perm
    for backend in auth.get_backends():
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\__init__.py", line 37, in get_backends
    return _get_backends(return_tuples=False)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\__init__.py", line 26, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\__init__.py", line 20, in load_backend
    return import_string(path)()
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_python3_ldap'
2020-12-27 17:54:07,054 django.request 224 ERROR    Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 251, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 502, in index
    app_list = self.get_app_list(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 485, in get_app_list
    app_dict = self._build_app_dict(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 430, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 546, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\models.py", line 312, in has_module_perms
    return _user_has_module_perms(self, app_label)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\models.py", line 215, in _user_has_module_perms
    for backend in auth.get_backends():
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\__init__.py", line 37, in get_backends
    return _get_backends(return_tuples=False)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\__init__.py", line 26, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\__init__.py", line 20, in load_backend
    return import_string(path)()
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_python3_ldap'
2020-12-27 18:02:24,107 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\settings\base.py changed, reloading.
2020-12-27 18:02:26,550 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 18:13:51,394 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 18:13:53,789 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 18:13:56,860 django.request 224 ERROR    Internal Server Error: /admin/interview/candidate/5/change/
Traceback (most recent call last):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 1568, in _changeform_view
    ModelForm = self.get_form(
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 679, in get_form
    readonly_fields = self.get_readonly_fields(request, obj)
  File "D:\Development\03 Django\recruitment\interview\admin.py", line 70, in get_readonly_fields
    group_names = self.get_group_names(request.user)
AttributeError: 'CandidateAdmin' object has no attribute 'get_group_names'
2020-12-27 18:14:42,826 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 18:14:45,676 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 18:16:35,609 django.request 224 ERROR    Internal Server Error: /admin/interview/candidate/5/change/
Traceback (most recent call last):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 1568, in _changeform_view
    ModelForm = self.get_form(
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 679, in get_form
    readonly_fields = self.get_readonly_fields(request, obj)
  File "D:\Development\03 Django\recruitment\interview\admin.py", line 70, in get_readonly_fields
    group_names = self.get_group_names(request.user)
AttributeError: 'CandidateAdmin' object has no attribute 'get_group_names'
2020-12-27 18:19:57,310 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 18:19:59,588 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 18:21:13,525 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:21:15,884 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:21:19,692 interview.admin 79 INFO     interviewer is in user's group for yoyo3_inter
2020-12-27 18:21:19,695 interview.admin 79 INFO     interviewer is in user's group for yoyo3_inter
2020-12-27 18:21:51,877 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:21:56,942 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:21:59,775 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:23:16,828 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:23:19,294 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:23:20,768 interview.admin 79 INFO     interviewer is in user's group for yoyo3_inter
2020-12-27 18:23:20,771 interview.admin 79 INFO     interviewer is in user's group for yoyo3_inter
2020-12-27 18:23:21,642 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:23:46,477 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:23:48,846 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:23:51,149 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:28:48,015 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 18:28:51,181 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 18:29:37,411 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:29:40,275 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:29:53,909 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 18:29:56,160 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 18:29:58,257 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:33:09,120 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 18:33:11,345 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 18:33:27,523 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:33:29,160 django.request 224 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "D:\Development\03 Django\recruitment\interview\admin.py", line 78, in get_changelist_instance
    self.list_editable = self.get_list_editable(request)
  File "D:\Development\03 Django\recruitment\interview\admin.py", line 74, in get_list_editable
    return self.default_list_editable
AttributeError: 'CandidateAdmin' object has no attribute 'default_list_editable'
2020-12-27 18:33:29,791 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:34:18,412 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 18:34:20,571 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 18:34:35,363 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 18:34:37,563 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 18:34:42,011 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:35:11,655 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:35:14,657 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 18:43:06,942 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 18:43:16,390 django.request 224 WARNING  Not Found: /
2020-12-27 18:43:35,517 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:12:10,259 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 19:12:45,386 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:12:47,754 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:12:53,902 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:13:53,756 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:13:55,825 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:14:00,210 interview.admin 116 INFO     interviewer is in user's group for yoyo3_inter
2020-12-27 19:14:00,212 interview.admin 116 INFO     interviewer is in user's group for yoyo3_inter
2020-12-27 19:14:00,963 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:14:20,008 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:20:39,937 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 19:20:42,366 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 19:22:35,171 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 19:22:37,376 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 19:22:47,642 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:22:49,198 django.request 224 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "D:\Development\03 Django\recruitment\interview\admin.py", line 109, in get_changelist_instance
    return super(CandidateAdmin, self).get_changelist_instance(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 731, in get_changelist_instance
    if self.get_actions(request):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 901, in get_actions
    actions = self._filter_actions_by_permissions(request, self._get_base_actions())
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 888, in _filter_actions_by_permissions
    if any(has_permission(request) for has_permission in permission_checks):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 888, in <genexpr>
    if any(has_permission(request) for has_permission in permission_checks):
  File "D:\Development\03 Django\recruitment\interview\admin.py", line 59, in has_export_permission
    return request.user.has_perm('%s %s' % (opts.app_lable, 'export'))
AttributeError: 'Options' object has no attribute 'app_lable'
2020-12-27 19:22:49,777 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:23:16,257 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:23:18,127 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:23:48,552 django.request 224 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "D:\Development\03 Django\recruitment\interview\admin.py", line 109, in get_changelist_instance
    return super(CandidateAdmin, self).get_changelist_instance(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 731, in get_changelist_instance
    if self.get_actions(request):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 901, in get_actions
    actions = self._filter_actions_by_permissions(request, self._get_base_actions())
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 888, in _filter_actions_by_permissions
    if any(has_permission(request) for has_permission in permission_checks):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 888, in <genexpr>
    if any(has_permission(request) for has_permission in permission_checks):
  File "D:\Development\03 Django\recruitment\interview\admin.py", line 59, in has_export_permission
    return request.user.has_perm('%s %s' % (opts.app_lable, 'export'))
AttributeError: 'Options' object has no attribute 'app_lable'
2020-12-27 19:24:38,424 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 19:24:40,775 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 19:24:42,699 django.request 224 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "D:\Development\03 Django\recruitment\interview\admin.py", line 109, in get_changelist_instance
    return super(CandidateAdmin, self).get_changelist_instance(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 731, in get_changelist_instance
    if self.get_actions(request):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 901, in get_actions
    actions = self._filter_actions_by_permissions(request, self._get_base_actions())
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 888, in _filter_actions_by_permissions
    if any(has_permission(request) for has_permission in permission_checks):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 888, in <genexpr>
    if any(has_permission(request) for has_permission in permission_checks):
  File "D:\Development\03 Django\recruitment\interview\admin.py", line 59, in has_export_permission
    return request.user.has_perm('%s.%s' % (opts.app_lable, 'export'))
AttributeError: 'Options' object has no attribute 'app_lable'
2020-12-27 19:27:18,684 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:27:20,231 django.request 224 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "D:\Development\03 Django\recruitment\interview\admin.py", line 109, in get_changelist_instance
    return super(CandidateAdmin, self).get_changelist_instance(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 731, in get_changelist_instance
    if self.get_actions(request):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 901, in get_actions
    actions = self._filter_actions_by_permissions(request, self._get_base_actions())
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 888, in _filter_actions_by_permissions
    if any(has_permission(request) for has_permission in permission_checks):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\contrib\admin\options.py", line 888, in <genexpr>
    if any(has_permission(request) for has_permission in permission_checks):
  File "D:\Development\03 Django\recruitment\interview\admin.py", line 59, in has_export_permission
    return request.user.has_perm('%s.%s' % (opts.app_lable, 'export'))
AttributeError: 'Options' object has no attribute 'app_lable'
2020-12-27 19:27:20,782 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:28:22,892 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\admin.py changed, reloading.
2020-12-27 19:28:25,083 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 19:28:28,572 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:28:44,500 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:28:46,635 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:29:12,670 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 19:53:26,904 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 20:06:22,438 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 20:06:55,870 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 20:06:59,610 django.security.SuspiciousSession 131 WARNING  Session data corrupted
2020-12-27 20:06:59,663 django.security.SuspiciousSession 131 WARNING  Session data corrupted
2020-12-27 20:07:00,642 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 20:07:11,272 django.security.SuspiciousSession 131 WARNING  Session data corrupted
2020-12-27 20:07:12,395 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 20:13:20,938 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\settings\local.py changed, reloading.
2020-12-27 20:13:24,098 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 20:15:12,025 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\interview\dingtalk.py changed, reloading.
2020-12-27 20:15:15,163 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 20:44:14,608 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 20:47:04,429 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 20:47:07,711 django.request 224 WARNING  Not Found: /account
2020-12-27 20:47:12,363 django.request 224 WARNING  Not Found: /account
2020-12-27 20:47:54,652 django.security.SuspiciousSession 131 WARNING  Session data corrupted
2020-12-27 20:48:20,196 django.security.SuspiciousSession 131 WARNING  Session data corrupted
2020-12-27 20:48:20,596 django.request 224 WARNING  Not Found: /
2020-12-27 20:48:21,095 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 20:49:02,624 django.request 224 WARNING  Not Found: /
2020-12-27 20:51:37,154 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\recruitment\urls.py changed, reloading.
2020-12-27 20:51:40,173 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 20:51:40,585 django.request 224 WARNING  Not Found: /
2020-12-27 20:51:42,515 django.request 224 WARNING  Not Found: /
2020-12-27 20:54:07,645 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\jobs\urls.py changed, reloading.
2020-12-27 20:54:10,049 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 20:54:23,924 django.request 224 WARNING  Not Found: /accounts/
2020-12-27 20:57:34,772 django.request 224 WARNING  Not Found: /accounts/loginout
2020-12-27 20:58:25,088 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 20:58:30,321 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 20:58:36,725 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:02:57,038 django.request 224 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'translate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Development\03 Django\recruitment\jobs\views.py", line 19, in joblist
    return HttpResponse(template.render(context))
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\loader_tags.py", line 213, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Jiang Zhongyang\AppData\Roaming\Python\Python38\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 8: 'translate', expected 'endblock'. Did you forget to register or load this tag?
2020-12-27 21:02:57,728 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:06:45,711 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:07:13,394 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:07:39,048 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:07:44,947 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:07:48,116 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:08:36,149 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:09:16,409 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:09:36,485 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:09:39,427 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:09:46,229 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:09:54,429 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:10:36,325 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:10:38,559 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:10:41,330 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:11:10,214 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:13:28,069 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:25:16,091 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\jobs\views.py changed, reloading.
2020-12-27 21:25:20,049 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 21:25:47,270 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:28:56,379 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\jobs\views.py changed, reloading.
2020-12-27 21:28:58,987 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 21:29:57,116 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:30:05,085 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:31:38,314 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:32:04,460 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:36:49,092 django.utils.autoreload 236 INFO     D:\Development\03 Django\recruitment\jobs\admin.py changed, reloading.
2020-12-27 21:42:17,791 django.utils.autoreload 612 INFO     Watching for file changes with StatReloader
2020-12-27 21:42:55,606 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:43:01,960 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:43:04,720 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:43:53,184 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:43:59,586 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:44:01,525 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:44:24,442 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:44:27,038 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:44:31,575 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:45:02,697 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:45:04,998 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:45:09,469 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:45:21,410 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:45:47,491 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:45:49,925 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:45:55,966 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:45:57,438 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:45:57,833 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:45:59,434 django.request 224 WARNING  Not Found: /favicon.ico
2020-12-27 21:46:01,208 django.request 224 WARNING  Not Found: /favicon.ico
